executor: CeleryExecutor

dags:
  gitSync:
    enabled: true
    repo: https://github.com/yousefessa2112/airflow-dags.git
    branch: main
    subPath: dags
    wait: 60
    depth: 1

webserver:
  enabled: true
  defaultUser:
    enabled: true
    username: admin
    password: admin

persistence:
  enabled: false

